fullnameOverride: php-api
image:
  repository: ghcr.io/asobitov2005/kube-php-api
  tag: 56f6ef1e1d08a3a551b303ad6a44a25f5fb66a54
containerPort: 8080
ingress:
  hosts:
    - host: php.example.com
      paths:
        - path: /
          pathType: Prefix
