fullnameOverride: python-api
image:
  repository: ghcr.io/asobitov2005/kube-python-api
  tag: 56f6ef1e1d08a3a551b303ad6a44a25f5fb66a54
containerPort: 8080
env:
  DB_HOST: postgres-pooler-rw.demo-apps.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: app
secretEnv:
  - name: DB_USER
    secretName: app-db-credentials
    key: username
  - name: DB_PASSWORD
    secretName: app-db-credentials
    key: password
ingress:
  hosts:
    - host: python.example.com
      paths:
        - path: /
          pathType: Prefix
