apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-web-services
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dotnet-api
          - name: python-api
          - name: node-api
          - name: go-api
          - name: java-api
          - name: php-api
          - name: ruby-api
          - name: rust-api
          - name: nginx-web
          - name: caddy-web
          - name: busybox-web
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/asobitov2005/kube.git
        targetRevision: main
        path: charts/web-service
        helm:
          valueFiles:
            - ../../apps/{{name}}/values.yaml
            - ../../environments/prod.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: demo-apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

