apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-ha
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/asobitov2005/kube.git
    targetRevision: main
    path: charts/rabbitmq-ha
    helm:
      valueFiles:
        - values.yaml
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

