fullnameOverride: java-api
image:
  repository: ghcr.io/asobitov2005/kube-java-api
  tag: local
containerPort: 8080
ingress:
  hosts:
    - host: java.example.com
      paths:
        - path: /
          pathType: Prefix
